'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FinalProjek.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1402008417() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1402008417", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _20140822_164451_angkringan_jacira() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20140822_164451_angkringan-jacira", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3f9470b34a8e3f526dbdb022f9f19cf7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3f9470b34a8e3f526dbdb022f9f19cf7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5a3761a6a5f842_1709260415135789186798() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5a3761a6a5f842.1709260415135789186798", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property contact_g222dd81fe_640() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact-g222dd81fe_640", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_financial_transaction_download_vector_credit_card_transactions_5a891ad9ec0e38_5271295115189347459669() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-financial-transaction-download-vector-credit-card-transactions-5a891ad9ec"& _ 
                        "0e38.5271295115189347459669", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_programmer_computer_programming_clip_art_admin_clipart_5b4ab080015921_3370205415316215040055() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-programmer-computer-programming-clip-art-admin-clipart-5b4ab080015921.337"& _ 
                        "0205415316215040055", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_property_management_real_estate_renting_landlord_landlords_5aeabae4b28a96_4004735715253327087313() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-property-management-real-estate-renting-landlord-landlords-5aeabae4b28a96"& _ 
                        ".4004735715253327087313", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2022_08_03_021517() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2022-08-03 021517", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_business_administration_icon_cms_icon_computer_ico_6025a3be739910_1818165516130794864735() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-business-administration-icon-cms-icon-computer-ico-6025a3be739910.181"& _ 
                        "8165516130794864735", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_info_icon_law_and_justice_icon_computer_icon_60cc3a438aeac4_651105781623996995569() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-info-icon-law-and-justice-icon-computer-icon-60cc3a438aeac4.651105781"& _ 
                        "623996995569", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_info_icon_law_and_justice_icon_computer_icon_60cc3a438aeac41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-info-icon-law-and-justice-icon-computer-icon-60cc3a438aeac41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_profits_icon_sales_icon_graph_icon_604216146b3dd1_8806067716149437644393() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-profits-icon-sales-icon-graph-icon-604216146b3dd1.8806067716149437644"& _ 
                        "393", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wan_alyasa_hotel_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wan-alyasa-hotel-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatsApp_Image_2022_12_26_at_21_34_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatsApp Image 2022-12-26 at 21.34.51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
